server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maojiawei/zhabei-spring-cloud-repo #default Config Server Uri
          search-paths: repos
      label: master
