server:
  port: 8080
spring:
  application:
      name: zhabei-client
  rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

