spring:
  application:
    name: server-zipkin
  rabbitmq:
    username: admin
    password: admin
  datasource:
    username: root
    password: Accp1234
    url: jdbc:mysql://localhost/zipkin?useUnicode=yes&autoReconnect=true&useSSL=false
    initialize: true
    schema:
      - classpath:zipkin.sql
    continueOnError: true
  sleuth:
    enabled: false
#zipkin:
#  storage:
#    type: mysql
server:
  port: 8889
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/